### ISSUE TITLE
Crash on startup - missing Waila?

### ISSUE THREAD

**Issue by trexxet** [Qwertygiy/qwertech#54]
Forge 10.13.4.1614, GT6 6.10.04, Waila 1.5.10
During construction phase:
```
[20:48:22] [Client thread/ERROR] [FML]: Caught exception from qwertech
java.lang.NoClassDefFoundError: mcp/mobius/waila/api/IWailaEntityProvider
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_181]
```

ouch:
```
[20:48:22] [Client thread/ERROR] [FML]: Caught exception from Waila
java.lang.NoClassDefFoundError: mcp/mobius/waila/api/IWailaEntityProvider
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_181]
```

Tried to remove Waila & Wawla, qwertech exception remains. 
Other mods:
```
	UC	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UC	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UC	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UC	FastCraft{1.25} [FastCraft] (fastcraft-1.25.jar) 
	UC	gregapi{GT6-MC1710} [Greg-API] (gregtech_1.7.10-6.10.04.jar) 
	UC	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.2308-universal.jar) 
	UC	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's+HarvestCraft+1.7.10Lb.jar) 
	UC	gregapi_post{GT6-MC1710} [Greg-API-Post] (gregtech_1.7.10-6.10.04.jar) 
	UC	gregtech{GT6-MC1710} [GregTech] (gregtech_1.7.10-6.10.04.jar) 
	UE	qwertech{1.0.0-a.47} [QwerTech] (qwertech-1.0.0-a.47.jar) 
	UE	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UE	wawla{1.3.1} [What Are We Looking At] (Wawla-1.0.5.120.jar) 
```

**Comment by Qwertygiy** [comment]
QwerTech is developed against Waila 1.5.11-RC2; I'll look at 1.5.10 and see if I can figure out what is missing, but in the meantime, I would suggest an upgrade: https://www.mobiusstrip.eu/maven/mcp/mobius/waila/Waila/1.5.11-RC2-NONEI_1.7.10/Waila-1.5.11-RC2-NONEI_1.7.10.jar

**Comment by trexxet** [comment]
Hmm, I've just updated Waila to this version and removed all other mods. However, the issue is still present.:
```
[22:04:36] [Client thread/ERROR] [FML]: Caught exception from Waila
java.lang.NoClassDefFoundError: mcp/mobius/waila/api/IWailaEntityProvider
```
```
[22:04:36] [Client thread/ERROR] [FML]: Caught exception from qwertech
java.lang.NoClassDefFoundError: mcp/mobius/waila/api/IWailaEntityProvider
```
```
	UC	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UC	gregapi{GT6-MC1710} [Greg-API] (gregtech_1.7.10-6.10.04.jar) 
	UC	gregapi_post{GT6-MC1710} [Greg-API-Post] (gregtech_1.7.10-6.10.04.jar) 
	UC	gregtech{GT6-MC1710} [GregTech] (gregtech_1.7.10-6.10.04.jar) 
	UE	qwertech{1.0.0-a.47} [QwerTech] (qwertech-1.0.0-a.47.jar) 
	UE	Waila{1.5.11} [Waila] (Waila-1.5.11-RC2-NONEI_1.7.10.jar) 
```
Looks like a Waila bug, but it seems that I'm the only one who have this issue.

**Comment by Qwertygiy** [comment]
Was a result of the order in which Forge loads mods, injects the sided proxy system, and incomplete use of reflection on my part interacting badly. Will be fixed in the next release.
